name: Slither Analysis

on:
  push:
    branches: [main]

jobs:
  slither-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install setuptools
        run: python -m pip install --upgrade pip setuptools

      - name: Install Slither
        run: pip install slither-analyzer

      - name: Run Slither
        run: slither "contracts/StaqeDeploy.sol" --exclude-informational
